// Code generated by gobind. DO NOT EDIT.

// Java class dummy.Conduit is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/vikulin/yggdrasil-extras/src/dummy
package dummy;

import go.Seq;

public final class Conduit implements Seq.Proxy {
	static { Dummy.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	Conduit(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public Conduit() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native void close() throws Exception;
	public native long read(byte[] p0) throws Exception;
	public native long write(byte[] p0) throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Conduit)) {
		    return false;
		}
		Conduit that = (Conduit)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Conduit").append("{");
		return b.append("}").toString();
	}
}

