// Code generated by gobind. DO NOT EDIT.

// Java class config.SwitchOptions is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/config
package config;

import go.Seq;

/**
 * SwitchOptions contains tuning options for the switch. These are advanced
options and shouldn&#39;t be changed unless necessary.
 */
public final class SwitchOptions implements Seq.Proxy {
	static { Config.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	SwitchOptions(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public SwitchOptions() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field SwitchOptions.MaxTotalQueueSize with unsupported type: uint64
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof SwitchOptions)) {
		    return false;
		}
		SwitchOptions that = (SwitchOptions)o;
		// skipped field SwitchOptions.MaxTotalQueueSize with unsupported type: uint64
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("SwitchOptions").append("{");
		return b.append("}").toString();
	}
}

