// Code generated by gobind. DO NOT EDIT.

// Java class mobile.MobileLogger is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/vikulin/yggdrasil-extras/src/mobile
package mobile;

import go.Seq;

public final class MobileLogger implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	MobileLogger(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public MobileLogger() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native long write(byte[] p0) throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof MobileLogger)) {
		    return false;
		}
		MobileLogger that = (MobileLogger)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("MobileLogger").append("{");
		return b.append("}").toString();
	}
}

