// Code generated by gobind. DO NOT EDIT.

// Java class dummy.DummyAdapter is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/vikulin/yggdrasil-extras/src/dummy
package dummy;

import go.Seq;

/**
 * DummyAdapter represents a running Dummy interface and extends the
yggdrasil.Adapter type. In order to use the Dummy adapter with Yggdrasil,
you should pass this object to the yggdrasil.SetRouterAdapter() function
before calling yggdrasil.Start().
 */
public final class DummyAdapter implements Seq.Proxy {
	static { Dummy.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	DummyAdapter(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public DummyAdapter() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native Conduit getConduit();
	public final native void setConduit(Conduit v);
	
	// skipped field DummyAdapter.Inbox with unsupported type: github.com/Arceliar/phony.Inbox
	
	// skipped method DummyAdapter.Act with unsupported parameter or return types
	
	// skipped method DummyAdapter.Init with unsupported parameter or return types
	
	/**
	 * IsTAP returns true if the adapter is a TAP adapter (Layer 2) or false if it
	is a TUN adapter (Layer 3).
	 */
	public native boolean isTAP();
	/**
	 * MTU gets the adapter&#39;s MTU. This can range between 1280 and 65535, although
	the maximum value is determined by your platform. The returned value will
	never exceed that of MaximumMTU().
	 */
	public native long mtu();
	/**
	 * Name returns the name of the adapter, e.g. &#34;dummy0&#34;. On Windows, this may
	return a canonical adapter name instead.
	 */
	public native String name();
	/**
	 * Start the setup process for the Dummy adapter. If successful, starts the
	reader actor to handle packets on that interface.
	 */
	public native void start() throws Exception;
	public native void stop() throws Exception;
	/**
	 * UpdateConfig updates the Dummy module with the provided config.NodeConfig
	and then signals the various module goroutines to reconfigure themselves if
	needed.
	 */
	public native void updateConfig(config.NodeConfig config);
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof DummyAdapter)) {
		    return false;
		}
		DummyAdapter that = (DummyAdapter)o;
		Conduit thisConduit = getConduit();
		Conduit thatConduit = that.getConduit();
		if (thisConduit == null) {
			if (thatConduit != null) {
			    return false;
			}
		} else if (!thisConduit.equals(thatConduit)) {
		    return false;
		}
		// skipped field DummyAdapter.Inbox with unsupported type: github.com/Arceliar/phony.Inbox
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getConduit()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("DummyAdapter").append("{");
		b.append("Conduit:").append(getConduit()).append(",");
		return b.append("}").toString();
	}
}

