// Code generated by gobind. DO NOT EDIT.

// Java class config.Config is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/config
package config;

import go.Seq;

public abstract class Config {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Config() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	/**
	 * Generates default configuration and returns a pointer to the resulting
	NodeConfig. This is used when outputting the -genconf parameter and also when
	using -autoconf.
	 */
	public static native NodeConfig generateConfig();
}
