// Code generated by gobind. DO NOT EDIT.

// Java class config.TunnelRouting is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/config
package config;

import go.Seq;

/**
 * TunnelRouting contains the crypto-key routing tables for tunneling regular
IPv4 or IPv6 subnets across the Yggdrasil network.
 */
public final class TunnelRouting implements Seq.Proxy {
	static { Config.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	TunnelRouting(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public TunnelRouting() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native boolean getEnable();
	public final native void setEnable(boolean v);
	
	// skipped field TunnelRouting.IPv6RemoteSubnets with unsupported type: map[string]string
	
	// skipped field TunnelRouting.IPv6LocalSubnets with unsupported type: []string
	
	// skipped field TunnelRouting.IPv4RemoteSubnets with unsupported type: map[string]string
	
	// skipped field TunnelRouting.IPv4LocalSubnets with unsupported type: []string
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof TunnelRouting)) {
		    return false;
		}
		TunnelRouting that = (TunnelRouting)o;
		boolean thisEnable = getEnable();
		boolean thatEnable = that.getEnable();
		if (thisEnable != thatEnable) {
		    return false;
		}
		// skipped field TunnelRouting.IPv6RemoteSubnets with unsupported type: map[string]string
		
		// skipped field TunnelRouting.IPv6LocalSubnets with unsupported type: []string
		
		// skipped field TunnelRouting.IPv4RemoteSubnets with unsupported type: map[string]string
		
		// skipped field TunnelRouting.IPv4LocalSubnets with unsupported type: []string
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getEnable()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("TunnelRouting").append("{");
		b.append("Enable:").append(getEnable()).append(",");
		return b.append("}").toString();
	}
}

