// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.DHTRes is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

/**
 * DHTRes represents a DHT response, as returned by DHTPing.
 */
public final class DHTRes implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	DHTRes(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public DHTRes() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field DHTRes.PublicKey with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.BoxPubKey
	
	// skipped field DHTRes.Coords with unsupported type: []uint64
	
	// skipped field DHTRes.Dest with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.NodeID
	
	// skipped field DHTRes.Infos with unsupported type: []github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.DHTEntry
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof DHTRes)) {
		    return false;
		}
		DHTRes that = (DHTRes)o;
		// skipped field DHTRes.PublicKey with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.BoxPubKey
		
		// skipped field DHTRes.Coords with unsupported type: []uint64
		
		// skipped field DHTRes.Dest with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.NodeID
		
		// skipped field DHTRes.Infos with unsupported type: []github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.DHTEntry
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("DHTRes").append("{");
		return b.append("}").toString();
	}
}

