// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.Dialer is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

/**
 * Dialer represents an Yggdrasil connection dialer.
 */
public final class Dialer implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	Dialer(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public Dialer() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped method Dialer.Dial with unsupported parameter or return types
	
	// skipped method Dialer.DialByNodeIDandMask with unsupported parameter or return types
	
	// skipped method Dialer.DialByPublicKey with unsupported parameter or return types
	
	// skipped method Dialer.DialContext with unsupported parameter or return types
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Dialer)) {
		    return false;
		}
		Dialer that = (Dialer)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Dialer").append("{");
		return b.append("}").toString();
	}
}

