// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.FlowKeyMessage is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

public final class FlowKeyMessage implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	FlowKeyMessage(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public FlowKeyMessage() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field FlowKeyMessage.FlowKey with unsupported type: uint64
	
	public final native byte[] getMessage();
	public final native void setMessage(byte[] v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof FlowKeyMessage)) {
		    return false;
		}
		FlowKeyMessage that = (FlowKeyMessage)o;
		// skipped field FlowKeyMessage.FlowKey with unsupported type: uint64
		
		byte[] thisMessage = getMessage();
		byte[] thatMessage = that.getMessage();
		if (thisMessage == null) {
			if (thatMessage != null) {
			    return false;
			}
		} else if (!thisMessage.equals(thatMessage)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getMessage()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("FlowKeyMessage").append("{");
		b.append("Message:").append(getMessage()).append(",");
		return b.append("}").toString();
	}
}

