// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.Listener is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

/**
 * Listener waits for incoming sessions
 */
public final class Listener implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	Listener(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public Listener() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped method Listener.Accept with unsupported parameter or return types
	
	// skipped method Listener.Addr with unsupported parameter or return types
	
	/**
	 * Close will stop the listener
	 */
	public native void close() throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Listener)) {
		    return false;
		}
		Listener that = (Listener)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Listener").append("{");
		return b.append("}").toString();
	}
}

