// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.Session is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

/**
 * Session represents an open session with another node. Sessions are opened in
response to traffic being exchanged between two nodes using Conn objects.
Note that sessions will automatically be closed by Yggdrasil if no traffic is
exchanged for around two minutes.
 */
public final class Session implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	Session(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public Session() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field Session.PublicKey with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.BoxPubKey
	
	// skipped field Session.Coords with unsupported type: []uint64
	
	// skipped field Session.BytesSent with unsupported type: uint64
	
	// skipped field Session.BytesRecvd with unsupported type: uint64
	
	// skipped field Session.MTU with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/types.MTU
	
	// skipped field Session.Uptime with unsupported type: time.Duration
	
	public final native boolean getWasMTUFixed();
	public final native void setWasMTUFixed(boolean v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Session)) {
		    return false;
		}
		Session that = (Session)o;
		// skipped field Session.PublicKey with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.BoxPubKey
		
		// skipped field Session.Coords with unsupported type: []uint64
		
		// skipped field Session.BytesSent with unsupported type: uint64
		
		// skipped field Session.BytesRecvd with unsupported type: uint64
		
		// skipped field Session.MTU with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/types.MTU
		
		// skipped field Session.Uptime with unsupported type: time.Duration
		
		boolean thisWasMTUFixed = getWasMTUFixed();
		boolean thatWasMTUFixed = that.getWasMTUFixed();
		if (thisWasMTUFixed != thatWasMTUFixed) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getWasMTUFixed()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Session").append("{");
		b.append("WasMTUFixed:").append(getWasMTUFixed()).append(",");
		return b.append("}").toString();
	}
}

