// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.SwitchQueues is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

/**
 * SwitchQueues represents information from the switch related to link
congestion and a list of switch queues created in response to congestion on a
given link.
 */
public final class SwitchQueues implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	SwitchQueues(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public SwitchQueues() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field SwitchQueues.Queues with unsupported type: []github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.SwitchQueue
	
	// skipped field SwitchQueues.Count with unsupported type: uint64
	
	// skipped field SwitchQueues.Size with unsupported type: uint64
	
	// skipped field SwitchQueues.HighestCount with unsupported type: uint64
	
	// skipped field SwitchQueues.HighestSize with unsupported type: uint64
	
	// skipped field SwitchQueues.MaximumSize with unsupported type: uint64
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof SwitchQueues)) {
		    return false;
		}
		SwitchQueues that = (SwitchQueues)o;
		// skipped field SwitchQueues.Queues with unsupported type: []github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.SwitchQueue
		
		// skipped field SwitchQueues.Count with unsupported type: uint64
		
		// skipped field SwitchQueues.Size with unsupported type: uint64
		
		// skipped field SwitchQueues.HighestCount with unsupported type: uint64
		
		// skipped field SwitchQueues.HighestSize with unsupported type: uint64
		
		// skipped field SwitchQueues.MaximumSize with unsupported type: uint64
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("SwitchQueues").append("{");
		return b.append("}").toString();
	}
}

