// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.SwitchPeer is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

/**
 * SwitchPeer represents a switch connection to a peer. Note that there may be
multiple switch peers per actual peer, e.g. if there are multiple connections
to a given node.

This struct is informational only - you cannot manipulate switch peer
connections using instances of this struct. You should use the AddPeer or
RemovePeer functions instead.
 */
public final class SwitchPeer implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	SwitchPeer(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public SwitchPeer() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field SwitchPeer.PublicKey with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.BoxPubKey
	
	// skipped field SwitchPeer.Coords with unsupported type: []uint64
	
	// skipped field SwitchPeer.BytesSent with unsupported type: uint64
	
	// skipped field SwitchPeer.BytesRecvd with unsupported type: uint64
	
	// skipped field SwitchPeer.Port with unsupported type: uint64
	
	public final native String getProtocol();
	public final native void setProtocol(String v);
	
	public final native String getEndpoint();
	public final native void setEndpoint(String v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof SwitchPeer)) {
		    return false;
		}
		SwitchPeer that = (SwitchPeer)o;
		// skipped field SwitchPeer.PublicKey with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.BoxPubKey
		
		// skipped field SwitchPeer.Coords with unsupported type: []uint64
		
		// skipped field SwitchPeer.BytesSent with unsupported type: uint64
		
		// skipped field SwitchPeer.BytesRecvd with unsupported type: uint64
		
		// skipped field SwitchPeer.Port with unsupported type: uint64
		
		String thisProtocol = getProtocol();
		String thatProtocol = that.getProtocol();
		if (thisProtocol == null) {
			if (thatProtocol != null) {
			    return false;
			}
		} else if (!thisProtocol.equals(thatProtocol)) {
		    return false;
		}
		String thisEndpoint = getEndpoint();
		String thatEndpoint = that.getEndpoint();
		if (thisEndpoint == null) {
			if (thatEndpoint != null) {
			    return false;
			}
		} else if (!thisEndpoint.equals(thatEndpoint)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getProtocol(), getEndpoint()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("SwitchPeer").append("{");
		b.append("Protocol:").append(getProtocol()).append(",");
		b.append("Endpoint:").append(getEndpoint()).append(",");
		return b.append("}").toString();
	}
}

