// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.TcpListener is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

/**
 * TcpListener is a stoppable TCP listener interface. These are typically
returned from calls to the ListenTCP() function and are also used internally
to represent listeners created by the &#34;Listen&#34; configuration option and for
multicast interfaces.
 */
public final class TcpListener implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	TcpListener(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public TcpListener() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field TcpListener.Listener with unsupported type: net.Listener
	
	public native void stop();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof TcpListener)) {
		    return false;
		}
		TcpListener that = (TcpListener)o;
		// skipped field TcpListener.Listener with unsupported type: net.Listener
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("TcpListener").append("{");
		return b.append("}").toString();
	}
}

