// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.TcpUpgrade is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

public final class TcpUpgrade implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	TcpUpgrade(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public TcpUpgrade() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof TcpUpgrade)) {
		    return false;
		}
		TcpUpgrade that = (TcpUpgrade)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("TcpUpgrade").append("{");
		return b.append("}").toString();
	}
}

