// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.Yggdrasil is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

public abstract class Yggdrasil {
	static {
		Seq.touch(); // for loading the native library
		config.Config.touch();
		_init();
	}
	
	private Yggdrasil() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	/**
	 * Minimum allowed total size of switch queues.
	 */
	public static final long SwitchQueueTotalMinSize = 4194304L;
	
}
