// Code generated by gobind. DO NOT EDIT.

// Java class mobile.Yggdrasil is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/vikulin/yggdrasil-extras/src/mobile
package mobile;

import go.Seq;

/**
 * Yggdrasil mobile package is meant to &#34;plug the gap&#34; for mobile support, as
Gomobile will not create headers for Swift/Obj-C etc if they have complex
(non-native) types. Therefore for iOS we will expose some nice simple
functions. Note that in the case of iOS we handle reading/writing to/from TUN
in Swift therefore we use the &#34;dummy&#34; TUN interface instead.
 */
public final class Yggdrasil implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	Yggdrasil(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public Yggdrasil() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	/**
	 * GetAddressString gets the node&#39;s IPv6 address
	 */
	public native String getAddressString();
	/**
	 * GetBoxPubKeyString gets the node&#39;s public encryption key
	 */
	public native String getBoxPubKeyString();
	public native String getCoordsString();
	public native String getPeersJSON();
	/**
	 * GetSigPubKeyString gets the node&#39;s public signing key
	 */
	public native String getSigPubKeyString();
	/**
	 * GetSubnetString gets the node&#39;s IPv6 subnet in CIDR notation
	 */
	public native String getSubnetString();
	public native String getSwitchPeersJSON();
	/**
	 * StartAutoconfigure starts a node with a randomly generated config
	 */
	public native dummy.ConduitEndpoint startAutoconfigure() throws Exception;
	/**
	 * StartJSON starts a node with the given JSON config. You can get JSON config
	(rather than HJSON) by using the GenerateConfigJSON() function
	 */
	public native dummy.ConduitEndpoint startJSON(byte[] configjson) throws Exception;
	/**
	 * Stop the mobile Yggdrasil instance
	 */
	public native void stop();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Yggdrasil)) {
		    return false;
		}
		Yggdrasil that = (Yggdrasil)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Yggdrasil").append("{");
		return b.append("}").toString();
	}
}

