// Code generated by gobind. DO NOT EDIT.

// Java class yggdrasil.DHTEntry is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil
package yggdrasil;

import go.Seq;

/**
 * DHTEntry represents a single DHT entry that has been learned or cached from
DHT searches.
 */
public final class DHTEntry implements Seq.Proxy {
	static { Yggdrasil.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	DHTEntry(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public DHTEntry() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field DHTEntry.PublicKey with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.BoxPubKey
	
	// skipped field DHTEntry.Coords with unsupported type: []uint64
	
	// skipped field DHTEntry.LastSeen with unsupported type: time.Duration
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof DHTEntry)) {
		    return false;
		}
		DHTEntry that = (DHTEntry)o;
		// skipped field DHTEntry.PublicKey with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/crypto.BoxPubKey
		
		// skipped field DHTEntry.Coords with unsupported type: []uint64
		
		// skipped field DHTEntry.LastSeen with unsupported type: time.Duration
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("DHTEntry").append("{");
		return b.append("}").toString();
	}
}

